import type { SkillDefinition, SkillId } from './types'

export const SKILLS: Record<SkillId, SkillDefinition> = {
  company_analysis: {
    id: 'company_analysis',
    label: '公司分析',
    description: '用于公司基本面、经营逻辑、竞争力与投资结论分析',
    requiredEvidence: ['financial_fact', 'research_view'],
    optionalEvidence: ['valuation_snapshot', 'annual_report_snippet', 'news_event'],
    bannedBehaviors: ['没有事实证据时下确定性结论', '忽略风险因素只输出正面逻辑'],
    outputSections: ['结论', '核心逻辑', '数据支撑', '风险与跟踪'],
    supportsFollowUp: true,
  },
  earnings_review: {
    id: 'earnings_review',
    label: '财报解读',
    description: '用于分析年报或季报的核心变化、驱动和持续性',
    requiredEvidence: ['annual_report_snippet', 'financial_fact'],
    optionalEvidence: ['research_view', 'news_event'],
    bannedBehaviors: ['未核对财报数据就总结业绩', '把管理层口径当作事实'],
    outputSections: ['结论', '核心财务数据', '变化原因', '持续性', '风险提示'],
    supportsFollowUp: true,
  },
  valuation: {
    id: 'valuation',
    label: '估值判断',
    description: '用于判断标的当前估值水平、历史位置与同业比较',
    requiredEvidence: ['valuation_snapshot'],
    optionalEvidence: ['peer_metric', 'financial_fact', 'research_view'],
    bannedBehaviors: ['没有估值数据时直接判断低估或高估', '只依据单一估值指标得出绝对结论'],
    outputSections: ['结论', '当前估值', '同业比较', '历史位置', '风险提示'],
    supportsFollowUp: true,
  },
  peer_comparison: {
    id: 'peer_comparison',
    label: '同行对比',
    description: '用于同业公司经营、财务和估值对比',
    requiredEvidence: ['peer_metric'],
    optionalEvidence: ['financial_fact', 'valuation_snapshot', 'research_view'],
    bannedBehaviors: ['没有同业样本就给出竞争排名'],
    outputSections: ['对比范围', '优势', '短板', '结论'],
    supportsFollowUp: true,
  },
  macro_analysis: {
    id: 'macro_analysis',
    label: '宏观分析',
    description: '用于分析宏观指标变化、趋势和市场含义',
    requiredEvidence: ['macro_series'],
    optionalEvidence: ['macro_signal', 'news_event', 'web_result'],
    bannedBehaviors: ['没有指标数据只凭常识讲宏观'],
    outputSections: ['现状', '变化', '传导逻辑', '关注点'],
    supportsFollowUp: true,
  },
  macro_to_asset: {
    id: 'macro_to_asset',
    label: '宏观传导',
    description: '用于分析宏观变量变化对行业或资产的传导影响',
    requiredEvidence: ['macro_series', 'macro_signal'],
    optionalEvidence: ['research_view', 'news_event'],
    bannedBehaviors: ['没有传导链条就直接推荐资产'],
    outputSections: ['变量变化', '传导路径', '受益/受损方向', '验证指标'],
    supportsFollowUp: true,
  },
  event_impact: {
    id: 'event_impact',
    label: '事件影响',
    description: '用于分析政策、新闻、公告等事件影响',
    requiredEvidence: ['news_event'],
    optionalEvidence: ['intelligence_note', 'research_view', 'financial_fact'],
    bannedBehaviors: ['只复述新闻不分析影响'],
    outputSections: ['事件摘要', '影响路径', '受影响对象', '风险与不确定性'],
    supportsFollowUp: true,
  },
  risk_diagnosis: {
    id: 'risk_diagnosis',
    label: '风险诊断',
    description: '用于识别公司、行业或宏观层面的关键风险',
    requiredEvidence: ['financial_fact'],
    optionalEvidence: ['research_view', 'news_event', 'intelligence_note'],
    bannedBehaviors: ['泛泛而谈风险', '不区分已发生风险和潜在风险'],
    outputSections: ['核心风险', '触发条件', '验证指标', '风险结论'],
    supportsFollowUp: true,
  },
  fact_check: {
    id: 'fact_check',
    label: '事实核验',
    description: '用于核验具体事实、数据点或观点是否有证据支持',
    requiredEvidence: ['financial_fact'],
    optionalEvidence: ['annual_report_snippet', 'research_view', 'news_event', 'macro_series'],
    bannedBehaviors: ['没有证据仍然给出肯定判断'],
    outputSections: ['核验结果', '证据', '结论'],
    supportsFollowUp: false,
  },
}
